{"timestamp":"2025-09-07T21:56:02.900110","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-09-07T21:56:02.900901","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/gtfs_realtime_dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-09-07T21:56:03.366657","level":"info","event":"Lecture des fichiers GTFS statiques...","logger":"root"}
{"timestamp":"2025-09-07T21:56:03.368046","level":"error","event":"Erreur fusion GTFS : [Errno 2] No such file or directory: 'gtfs_static/stop_times.txt'","logger":"root"}
{"timestamp":"2025-09-07T21:56:03.368248","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"RuntimeError","exc_value":"Fusion impossible : [Errno 2] No such file or directory: 'gtfs_static/stop_times.txt'","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":920,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1215,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/scripts/fused_gtfs.py","lineno":54,"name":"fuse_gtfs"}],"is_group":false,"exceptions":[]},{"exc_type":"FileNotFoundError","exc_value":"[Errno 2] No such file or directory: 'gtfs_static/stop_times.txt'","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/opt/airflow/scripts/fused_gtfs.py","lineno":16,"name":"fuse_gtfs"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py","lineno":948,"name":"read_csv"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py","lineno":611,"name":"_read"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py","lineno":1448,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py","lineno":1705,"name":"_make_engine"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py","lineno":863,"name":"get_handle"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-09-07T21:56:03.369737","level":"error","event":"Failed to run task callback","kind":"on_failure_callback","index":0,"callback":"<function alert_if_failed at 0x7e0c46694180>","logger":"task","error_detail":[{"exc_type":"TypeError","exc_value":"alert_if_failed() takes 0 positional arguments but 1 was given","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1152,"name":"_run_task_state_change_callbacks"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"}],"is_group":false,"exceptions":[]}]}
